Ejercicios/Ejercicios.Unidad2/Controllers/Api/CustomersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Ejercicios.Unidad2.Models;
using System.Web.Http;
using AutoMapper;
using Ejercicios.Unidad2.Dtos;
using Microsoft.EntityFrameworkCore;
using RouteAttribute = Microsoft.AspNetCore.Mvc.RouteAttribute;
using HttpPostAttribute = Microsoft.AspNetCore.Mvc.HttpPostAttribute;
using HttpPutAttribute = Microsoft.AspNetCore.Mvc.HttpPutAttribute;
using HttpDeleteAttribute = Microsoft.AspNetCore.Mvc.HttpDeleteAttribute;

namespace Ejercicios.Unidad2.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class CustomersController : ControllerBase
    {
        private VidlyDBContext _context;
        private IMapper _mapper;

        public CustomersController(VidlyDBContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        public IEnumerable<CustomerDto> Get(string query = null)
        {
            // var customers= _context.Customer
            //     .Include(c => c.MembershipType)
            //     .ToList()
            //     .Select(_mapper.Map<Customer, CustomerDto>);
            //
            // return Ok(customers);

            //TODO no anda. tuve que agregar were para que anda sino no funcionaba.
            var customerQuery = _context.Customer
                .Include(c => c.MembershipType)
                .Where(c => c.Id != 0);
            
            if (!String.IsNullOrWhiteSpace(query))
                customerQuery = customerQuery.Where(c => c.Name.Contains(query));
            
            return customerQuery
                .ToList()
                .Select(_mapper.Map<Customer, CustomerDto>);
            
            // return Ok(customerDtos);
        }

        [Route("{id}")]
        public IActionResult Get(int id)
        {
            var customer = _context.Customer.SingleOrDefault(c => c.Id == id);

            if (customer == null)
                return NotFound();

            return Ok(_mapper.Map<Customer, CustomerDto>(customer));
        }

        [HttpPost]
        //TODO deberia usar IHttpActionResulta pero no funciona "return BadRequest()"
        public IActionResult CreateCustomer(CustomerDto customerDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var customer = _mapper.Map<CustomerDto, Customer>(customerDto);
            _context.Customer.Add(customer);
            _context.SaveChanges();

            customerDto.Id = customer.Id;
            
            return Created(new Uri($"{Request.Path}/{customer.Id}", UriKind.Relative), customerDto);
        }

        [HttpPut]
        [Route("{id}")]
        public IActionResult UpdateCustomer(int id, CustomerDto customerDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var customerIdDb = _context.Customer.SingleOrDefault(c => c.Id == id);

            if (customerIdDb == null)
                return NotFound();

            _mapper.Map(customerDto, customerIdDb);
            
            //Se reemplaza por el mapeo
            // customerIdDb.Name = customerDto.Name;
            // customerIdDb.Birthdate = customerDto.Birthdate;
            // customerIdDb.IsSubscribedToNewsletter = customerDto.IsSubscribedToNewsletter;
            // customerIdDb.MembershipTypeId = customerDto.MembershipTypeId;


            _context.SaveChanges();

            return Ok();
        }

        [HttpDelete]
        [Route("{id}")]
        public IActionResult DeleteCustomer(int id)
        {
            var customerIdDb = _context.Customer.SingleOrDefault(c => c.Id == id);

            if (customerIdDb == null)
                return NotFound();

            _context.Customer.Remove(customerIdDb);
            _context.SaveChanges();

            return Ok();
        }

    }
}

Ejercicios/Ejercicios.Unidad2/Controllers/Api/MoviesController.cs
using Ejercicios.Unidad2.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Ejercicios.Unidad2.Dtos;
using Microsoft.EntityFrameworkCore;

namespace Ejercicios.Unidad2.Controllers.Api
{

    [Route("api/[controller]")]
    [ApiController]
    public class MoviesController : ControllerBase
    {
        private VidlyDBContext _context;
        private IMapper _mapper;

        public MoviesController(VidlyDBContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        public IEnumerable<MovieDto> Get(string query = null)
        {
            var moviesQuery = _context.Movie
                .Include(m => m.Genre)
                .Where(m => m.NumberAvailable > 0);

            if (!String.IsNullOrWhiteSpace(query))
                moviesQuery = moviesQuery.Where(m => m.Name.Contains(query));

            return moviesQuery
                .ToList()
                .Select(_mapper.Map<Movie, MovieDto>);
        }

        [Route("{id}")]
        public IActionResult Get(int id)
        {
            var movie = _context.Movie.SingleOrDefault(m => m.Id == id);

            if (movie == null)
                return NotFound();

            return Ok(_mapper.Map<Movie, MovieDto>(movie));
        }

        [HttpPost]
        public IActionResult CreateMovie(MovieDto movieDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var movie = _mapper.Map<MovieDto, Movie>(movieDto);
            movie.DateAdded = DateTime.Now;
            _context.Movie.Add(movie);
            _context.SaveChanges();

            movieDto.Id = movie.Id;

            return Created(new Uri($"{Request.Path}/{movie.Id}", UriKind.Relative), movieDto);
        }


        [HttpPut]
        [Route("{id}")]
        public IActionResult UpdateMovie(int id, MovieDto movieDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var movieInDb = _context.Movie.SingleOrDefault(m => m.Id == id);

            if (movieInDb == null)
                return NotFound();

            _mapper.Map(movieDto, movieInDb);

            _context.SaveChanges();

            return Ok();
        }


        [HttpDelete]
        [Route("{id}")]
        public IActionResult DeleteMovie(int id)
        {
            var movieIdDb = _context.Movie.SingleOrDefault(m => m.Id == id);

            if (movieIdDb == null)
                return NotFound();

            _context.Movie.Remove(movieIdDb);
            _context.SaveChanges();

            return Ok();
        }
    }
}

Ejercicios/Ejercicios.Unidad2/Controllers/RentalsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ejercicios.Unidad2.Filter;

namespace Ejercicios.Unidad2.Controllers
{
    [IsAdmin]
    public class RentalsController : Controller
    {
        public IActionResult New()
        {
            return View();
        }
    }
}

Ejercicios/Ejercicios.Unidad2/Views/Shared/_AdminNavBar.cshtml
@using Microsoft.AspNetCore.Http
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Customers" asp-action="Index">Vidly</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Rentals" asp-action="New">New Rental</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="nav-link d-flex">@Context.Session.GetString("UserName")</a>
                    </li>
                    <li>
                        <a class="nav-link d-flex" asp-area="" asp-controller="User" asp-action="LogOut">Log Out</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

Ejercicios/Ejercicios.Unidad2/Views/Shared/_CustomerNavBar.cshtml
@using Microsoft.AspNetCore.Http;
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">Vidly</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="nav-link d-flex">@Context.Session.GetString("UserName")</a>
                    </li>
                    <li>
                        <a class="nav-link d-flex" asp-area="" asp-controller="User" asp-action="LogOut">Log Out</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

Ejercicios/Ejercicios.Unidad2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vidly</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/typehead.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css"/>
</head>
<body>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Vidly - Facundo Marin
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Para usar BOOTBOX model popup-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>
    <!-- Para usar DATATABLES-->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
      
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/typehead.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Ejercicios/Ejercicios.Unidad2/Views/Shared/_NavBar.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Customers" asp-action="Index">Vidly</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="User" asp-action="Login">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="User" asp-action="Register">Register</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>