Ejercicios/Vuelos/Models/ErrorViewModel.cs
using System;

namespace Vuelos.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Ejercicios/Vuelos/Controllers/VuelosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Repository;
using Repository.Models;

namespace Vuelos.Controllers
{
    public class VuelosController : Controller
    {
        private IVueloRepository _vueloRepository;

        public VuelosController(IVueloRepository vueloRepository)
        {
            _vueloRepository = vueloRepository;
        }

        public IActionResult Index()
        {
            IEnumerable<Vuelo> vuelos = _vueloRepository.GetVuelos();
            return View(vuelos);
        }

        public IActionResult Create()
        {
            return View("VuelosForm");
        }

        [HttpPost]
        public IActionResult Create(CreateVueloModel model)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Create", model);

            _vueloRepository.Create(model);

            return RedirectToAction("Index");
        }

        
        public IActionResult Edit(int id)
        {
            var vuelo = _vueloRepository.GetById(id);
            return View("Edit",vuelo);
        }

        [HttpPost]
        public IActionResult Edit(Vuelo vuelo)
        {
            _vueloRepository.Edit(vuelo);
            return RedirectToAction("Index");
        }

        public IActionResult Delete()
        {
            var vuelos = _vueloRepository.GetVuelos();

            return View(vuelos);

        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var vuelo = _vueloRepository.GetById(id);
            if (vuelo == null)
                return RedirectToAction("Delete");

            _vueloRepository.Delete(vuelo);
            return RedirectToAction("Index");
        }
    }
}

Ejercicios/Vuelos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vuelos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-dark navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Vuelos" asp-action="Index">Vuelos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Vuelos" asp-action="Create">Alta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Vuelos" asp-action="Delete">Baja</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Vuelos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Ejercicios/Vuelos/Views/Vuelos/Delete.cshtml
@model IEnumerable<Repository.Vuelo>

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Vuelo</h1>
<hr/>

<form asp-action="Delete" asp-controller="Vuelos">
    <select name="id">
        <option selected>Seleccione vuelo que desee borrar.</option>
        @foreach (var vuelo in @Model)
        {
            <option value="@vuelo.Id">@vuelo.NumeroVuelo</option>
        }
    </select>
    <button type="submit" class="btn btn-primary">Delete</button>

</form>

Ejercicios/Vuelos/Views/Vuelos/Edit.cshtml
@model Repository.Vuelo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit @Model.NumeroVuelo</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NumeroVuelo" class="control-label"></label>
                <input asp-for="NumeroVuelo" class="form-control" />
                <span asp-validation-for="NumeroVuelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HorarioLlegada" class="control-label"></label>
                <input asp-for="HorarioLlegada" class="form-control" />
                <span asp-validation-for="HorarioLlegada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LineaAerea" class="control-label"></label>
                <input asp-for="LineaAerea" class="form-control" />
                <span asp-validation-for="LineaAerea" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Demora" /> @Html.DisplayNameFor(model => model.Demora)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ejercicios/Vuelos/Views/Vuelos/Index.cshtml
@model IEnumerable<Repository.Vuelo>

@{
    ViewData["Title"] = "Index";
}

<h1>Próximos vuelos</h1>
<hr />
<div>
    <table class="table table-bordered table-hover">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Horario Llegada</th>
            <th scope="col">Vuelo</th>
            <th scope="col">Línea Aerea</th>
            <th scope="col">Demora</th>
            @* <th scope="col">Editar</th> *@
        </tr>
        </thead>
        <tbody>
        @foreach (var vuelo in @Model)
        {
           
                <tr  onclick="irAEvento('/Vuelos/Edit/@vuelo.Id')">
                    <th>@vuelo.HorarioLlegada.ToShortTimeString()</th>
                    <td>@vuelo.NumeroVuelo</td>
                    <td>@vuelo.LineaAerea</td>
                    <td>@(vuelo.Demora ? "Si" : "No")</td>
                    @* <td>@Html.ActionLink("Editar", "Edit", "Vuelos", new{@vuelo.Id})</td> *@
                </tr>
            
        }
        </tbody>
    </table>
    
    
</div>

Ejercicios/Vuelos/Views/Vuelos/VuelosForm.cshtml
@model Repository.Models.CreateVueloModel

@{
    ViewData["Title"] = "Create";
}

<h1>Crear Vuelo</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NumeroVuelo" class="control-label"></label>
                <input asp-for="NumeroVuelo" class="form-control" />
                <span asp-validation-for="NumeroVuelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HorarioLlegada" class="control-label"></label>
                <input asp-for="HorarioLlegada" class="form-control" />
                <span asp-validation-for="HorarioLlegada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LineaAerea" class="control-label"></label>
                <input asp-for="LineaAerea" class="form-control" />
                <span asp-validation-for="LineaAerea" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Demora" /> @Html.DisplayNameFor(model => model.Demora)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}